name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate random secret
        id: secret
        run: echo "password=$(openssl rand -hex 16)" >> $GITHUB_OUTPUT

      - name: Run tests
        run: pnpm test
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_PAT }}
          SECRET_COOKIE_PASSWORD: ${{ steps.secret.outputs.password }}

      - name: Build application
        run: pnpm run build
        env:
          SECRET_COOKIE_PASSWORD: ${{ steps.secret.outputs.password }}

      - name: Check build artifacts
        run: |
          if [ ! -d ".next" ]; then
            echo "Build failed - .next directory not found"
            exit 1
          fi
          echo "Build successful - .next directory exists"
